### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by briandpassa** [Crazywater/knuffiworkout#1] opened 2019-05-20 11:54 UTC
My apologies newbie here. 

_Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri =http://127.0.0.1:1025/ek6BYVm_rD0=/ws_

That's the result of flutter run without changing anything to the source code. What might be the issue?

**Comment by Crazywater** [comment] 2019-05-26 08:51
Hmm, this does not sound specific to this project. Does an empty Flutter project work on your machine?

It might be something firewall related, what platform are you running on?

**Comment by Crazywater** [comment] 2019-05-26 08:54
I also found this issue:
https://github.com/flutter/flutter/issues/32587

Does it work on a real device instead of an emulator, or on an emulator with Android 9.0 (API version 28)?

**Comment by Crazywater** [comment] 2019-06-07 08:58
Closing this one, since it's most likely a duplicate of https://github.com/flutter/flutter/issues/32587 - please follow there.

**Closed as completed by Crazywater** 2019-06-07 08:58 UTC
